name: flutex_admin
description: "Perfex CRM Admin / Staff Mobile App for Android & IOS"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.1+1

environment:
  sdk: ^3.8.1
  
dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  http: ^1.4.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  connectivity_plus: ^6.1.4
  introduction_screen: ^3.1.17
  date_field: ^6.0.3+1
  flutter_html: ^3.0.0
  multi_dropdown: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^5.1.1
  flutter_widget_from_html: ^0.16.0
  syncfusion_flutter_charts: ^29.2.10
  flutter_boardview: ^0.2.1
  table_calendar: ^3.2.0
  timelines_plus: ^1.0.7
  async: ^2.13.0
  html: ^0.15.6
  file_picker: ^10.2.0
  firebase_core: ^4.2.1
  local_auth: 2.2.0
  geolocator: ^13.0.2
  battery_plus: ^6.2.1
  workmanager: ^0.9.0+3
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.0.2
  wakelock_plus: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animation/
    - assets/lang/
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
          weight: 700
